In [12]:
import numpy as np
arr1=[[22,28,34]]
arr2=np.zeros((50,))
arr3=[[22,34],[7,14],[56,84]]
arr4=np.dot(arr1,arr3)
if np.shape(arr4)==(1,2) and arr2[4]!=0:
  print("Passed")
else:
  print("Fail")

Passed


In [13]:
arr1

[[22, 28, 34]]

In [14]:
arr2

array([ 0.,  0.,  0.,  0., 28.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
arr3

[[22, 34], [7, 14], [56, 84]]

In [16]:
arr4

array([[2584, 3996]])

In [17]:
arr2[4]=28
arr2

array([ 0.,  0.,  0.,  0., 28.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
import numpy as np
array=np.identity(3)
array2=array.copy()
array2*= 9
array2+= 1
array3=np.dot(array,array2)
print(f"Identity Matrix I = \n {array}")
print(f"Matrix 9I+1 = \n {array2}")
print(f"I * (9I+1) = \n {array3}")

Identity Matrix I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix 9I+1 = 
 [[10.  1.  1.]
 [ 1. 10.  1.]
 [ 1.  1. 10.]]
I * (9I+1) = 
 [[10.  1.  1.]
 [ 1. 10.  1.]
 [ 1.  1. 10.]]
